spring:
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/ecommerce_prod}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:}
  sql:
    init:
      mode: never

  # Disable development features
  devtools:
    restart:
      enabled: false

# Production logging
logging:
  level:
    root: WARN
    com.daemonsoft.ecommerce: INFO
    org.springframework.r2dbc: WARN
    io.r2dbc: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Production server settings
server:
  port: ${PORT:8080}
  shutdown: graceful


# Application-specific configuration
app:
  error-handling:
    include-stack-trace: false 
