spring:
  application:
    name: ecommerce-prices-service
  r2dbc:
    url: r2dbc:h2:mem:///ecommerce_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  webflux:
    base-path: /api
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Server configuration
server:
  port: 8080
  shutdown: graceful

# Logging configuration
logging:
  level:
    root: INFO
    com.daemonsoft.ecommerce: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.h2: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# API documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Application-specific configuration
app:
  request-tracing:
    header-name: X-Request-Id
  error-handling:
    include-stack-trace: false
